export const ADD_TO_CART='ADD_TO_CART';
export const INCREASE_QUANTITY='INCREASE_QUANTITY';
export const DECREASE_QUANTITY='DECREASE_QUANTITY';
export const DELETE_CART_ITEM='DELETE_CART_ITEM';
export const CHANGE_MESSAGE='CHANGE_MESSAGE';